title: Nikhil Raj A
email: nikhilrajnair.a@gmail.com
description: "Frontend Developer with 7+ years experience in Angular, Ember.js, and React."
baseurl: "" #
url: "https://nikhilrajnair.github.io"
theme: minima
